### ISSUE TITLE
TO DO: Double logistic selectivity parameterization

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [brianlangseth-NOAA/Spatial-Workshop-SPASAM#21]
Separate from #5. Double logistic selectivity is not parameterized correction. Current parameterization, which only has positive parameters because everything is on log scale and exp() of any number can only be positive, results in a logistic function always.

- [x] (Jon) Need to parameterize so that with positive only parameters, function can be 4-parameter double logistic. Done in commit [c43dc7d](https://github.com/brianlangseth-NOAA/Spatial-Workshop-SPASAM/commit/c43dc7d98278a7cf1c6248da71d13d3763dbda40)
- [x] (Brian) Need to rescale to maximum so that maximum selectivity is set to 1. Done in commit https://github.com/brianlangseth-NOAA/Spatial-Workshop-SPASAM/commit/cd2f8844f95780f2ac03ed64d64323fb3cbbab96

**Comment by brianlangseth-NOAA** [comment]
@JDeroba I am trying to work on rescaling selectivity but I cant even cout the maximum value of the function

I tried setting up a temporary variable for survey_selectivity and then call the max function
cout << "Max survey select " << max(survey_selectivity_temp(j,r,y,a,z)) << endl;

I get the following error 
YFT_1area.cpp:2168:87: error: no matching function for call to 'max(prevariable)'

ADMB is registering the dvariable max(.... function within fvar.hpp so it seems like I need to have it be a dvariable instead? Im not sure how to do this. Do you know how to resolve?

**Comment by JDeroba** [comment]
@brianlangseth-NOAA You might recall that I briefly tried to get selectivity rescaled too. I failed at this error message. After some sleuthing, I reached the conclusion that the max function doesn't work at all for anything bigger than a matrix or vector; i.e., max won't work on these big arrays. I even tried by hard coding some of the looping variables, e.g., max(survey_selectivity_temp(1,1,1,a,1)), and I got the same error message. I looked at Legault's ASAP code and he always reduces arrays and matrices to a single vector of selectivity at age before taking the max. So for us, that might involve making a temporary vector within a loop, as a rough example: temp_sel(a)=survey_selectivity_temp(1,1,1,a,1) and then max(temp_sel). We probably don't actually want to hard code all the ones in survey_selectivity_temp(1,1,1,a,1), but rather deal with the other elements of the array within the loops maybe. I'm not sure. In short, I think we need to get down to a single vector for the max to work. You could probably try that pretty quickly in your cout and see what happens. I'll email Legault to see if he has any insight.

**Comment by brianlangseth-NOAA** [comment]
@JDeroba I see Legault's response. I will try both options today

**Comment by brianlangseth-NOAA** [comment]
@JDeroba: selectivities are rescaled as of commit https://github.com/brianlangseth-NOAA/Spatial-Workshop-SPASAM/commit/cd2f8844f95780f2ac03ed64d64323fb3cbbab96 per our standard of updating the .tpl and .exe for the root Estimation_Model folder. I also updated the tpl and exe with these changes within YFT_1area >> Estimation_Model, but did so in a separate commit. 

The total lines of code hide the amount of collective time it took to resolve this issue. Its nice to have it resolved and closed!

**Comment by JDeroba** [comment]
Brian,
Great work! Definitely nice to have this resolved! We leave for vacation
this Friday (visiting my folks and trout fishing at the cabin) and I'm not
sure I'll get back to this before then. But, if I do, then I'll revisit my
failed attempts at estimating reasonable fishery selectivities. I suspect
something else is still wrong with those, but all in good time.

JJD
