### ISSUE TITLE
try a single fleet

### ISSUE THREAD

**Issue by JDeroba** [brianlangseth-NOAA/Spatial-Workshop-SPASAM#25]
7 fleets * 256 years is 1,792 parameters and will likely continue to cause huge issues of long run-times. Consider reducing to a single fleet by summing annual catches and calculating comps as catch weighted values for each year.

**Comment by JDeroba** [comment]
One problem with this idea is that as the proportion of catch coming from different fleets changes through time, it will induce time varying selectivity, which we currently don't have the capability to estimate. So we could 1) estimate time invariant selectivity, live with it, and see what happens knowing it's wrong, 2) try to add time varying selectivity, which I'm not excited about.

**Comment by JDeroba** [comment]
Or instead of a single fleet, combine fleets with similar selectivity, which would reduce or eliminate the time varying selectivity concern.

**Comment by brianlangseth-NOAA** [comment]
The current best option for the model is one starting after all 0 catches in the model. This removes the first 105 years of data. The selectivity estimating in that model (when Rdevs were also esitmated) are shown here
![image](https://user-images.githubusercontent.com/27824606/170747825-376eb5d7-7e5f-4ecf-9870-bc71120400a2.png)

This suggests we could combine fleets 4 and 6, and 2 and 7. Possibly we could even go so far as combining fleet 1 along with fleets 2 and 7. Regardless, going from 7 fleets to even 5 fleets would save some parameters and run time.

**Comment by JDeroba** [comment]
We tried a four fleet model and it somehow had more problems than a 7 fleet version. For example, the four fleet model has scale instability and did not find the same solution when I did a simple jitter analysis on starting values of beta3 and beta4 of the dbl logistic selectivity. Using a 7 fleet model is less problematic at this point because we were able to speed up run time (see #37 )
