### ISSUE TITLE
allow survey selectivity to mirror a fishery

### ISSUE THREAD

**Issue by JDeroba** [brianlangseth-NOAA/Spatial-Workshop-SPASAM#27]
In the case of YFT, the only index is a fishery dependent CPUE with the same age composition and selectivity as one of the fishing fleets. We should add the capability for a survey to have the same selectivity as a fishery so that we are not unnecessarily estimating the same selectivity parameters twice (once for survey and once for fishery). @brianlangseth-NOAA

**Comment by brianlangseth-NOAA** [comment]
When mirroring, we need to ensure the phases for survey selectivity parameters are negative. Otherwise the parameter is estimated and those estimates dont matter. Thus resolve by not estimating.
