### ISSUE TITLE
Initial abundance issues?

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [brianlangseth-NOAA/Spatial-Workshop-SPASAM#32]
Our initial abundance (as established by decaying from R0) shows higher abundance around age 6 than for age 5. How can this be if the age composition is based on using mortality to decay from R0. Do we have a non-zero mortality rate? The same is true for ages 19-22 (but not easily seen in figure)

![image](https://user-images.githubusercontent.com/27824606/168329046-18b483d3-c121-4eba-a9de-80250e878e86.png)

**Comment by brianlangseth-NOAA** [comment]
Although the process is a tad confusing deviations in Ninit are allowed.  I haven't yet tried to include Ndevs. Right now we decay from R0 based on natural mortality by age, which doesn't use any deviations.

If each age is decayed based on the M from previous ages, the only way for initial abundance to be higher than a previous age would be to have negative mortality. Thus, I wonder if a constant M is assumed for all ages before, or whether there is some other minor error.

**Comment by brianlangseth-NOAA** [comment]
M is assumed to the be the same for the age at which M is defined AND for all ages before. For example, for M at age = 0.3, 0.27, 0.24, 0.21..., 0.27 is applied for all years (1) before. Consequently, one can obtain increase amounts of decay because as M linearly declines, exp(-M) is decreasing less and less, and so raising it to an increasing power results in a parabolic curve that starts to increase. 

Is applying M to all years before it appropriate? Seems like M should change for each year going back in the past.

**Comment by JDeroba** [comment]
We could just average among across ages and use an age-invariant M. This will produce an identical fit to an age-varying M that is not being estimated. Deroba and Schueller 2013, Performance of stock assessments with misspecified age- and time-varying natural mortality, Fisheries Research 146 27-40.

**Comment by brianlangseth-NOAA** [comment]
This issue is not as relevant given the finding that estimating Ndevs is doable in issue #37 with other changes to speed up the runtime. With our decision to use a shortened time series, Ndevs is even more appropriate to estimate, thus setting to a decay based on mortality is not as relevant. If however we do ever set to a decay function, the issue raised here should be revisted.
