### ISSUE TITLE
Add the 100 data sets to the analysis

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [brianlangseth-NOAA/Spatial-Workshop-SPASAM#38]
Have used 1 dataset for the 1 area model now need to functionalize the use of the 100 dataset scenario

**Comment by brianlangseth-NOAA** [comment]
@JDeroba or @AmySchueller-NOAA do either of you have existing R code that compiles a .tpl file and builds the .exe file within R?

**Comment by JDeroba** [comment]
No. I've never even tried.

**Comment by brianlangseth-NOAA** [comment]
Thanks you two. @AmySchueller-NOAA Can you attach the code?

**Comment by brianlangseth-NOAA** [comment]
Use `shell(paste0("admb ",mod_name))`
