### ISSUE TITLE
Add the 4 area data sets

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [brianlangseth-NOAA/Spatial-Workshop-SPASAM#39]

**Comment by brianlangseth-NOAA** [comment]
There are two pertinent area representations in our OM-EM structure for the 4 area model: metapopluation (multiple subpopulations with unique demographics/vital rates) or spatial heterogeneity (one population with multiple regions).

Because the biological data provided for YFT does not change by area, I'm assuming our structure is spatial heterogeneity.

**Comment by brianlangseth-NOAA** [comment]
Need to figure out a solution for overcoming the limitation currently that there needs to be the same number of fleets by region. 

The OM.dat file has the following

# TO BE SAFE, IF RUNNING EMs, THEN OM AND EM SHOULD BE PARAMETRIZED TO HAVE THE SAME NUMBER OF REGIONS IN EVERY POPULATION AND THE SAME NUMBER OF FLEETS IN EVERY REGION/POPULATION

# NOTE: For each parameter listed below the estimated parameter array has dimensions equal to number of regions or fleets in the first population/region
#       IF number of regions or fleets differ in other populations or regions, then EM will likely crash when trying to assign estimated parameters to associated arrays

**Comment by brianlangseth-NOAA** [comment]
Dan's solutions, from email on 9/15

So, if I remember correctly this issue is mostly due to ADMB not allowing high dimensional ragged arrays for estimated parameters. I think it could be coded within a matrix of estimated parameters using complicated indices as is done with some of the other parameters, but not positive. I think I was just lazy and foresaw few situations where I would actually bother to have differing number of regions or fleets (since I never envisioned this as a true assessment 'platform'). 

I have a couple recommendations. First, I know that I reported the issue of high dimensional arrays to the developers and they fixed it for some things like derived values (you can check the ADMB 11 updates and you should see some stuff about 6d and 7d arrays, which was thanks to us), which would have made a lot of the tagging and likelihood code simpler if they existed a few years ago. But, I don't know if they ever got to the point of allowing ragged arrays for estimated parameters. It might be worth reaching out to ask about and/or see if there are any plans to do that sort of thing. I'm guessing probably not, so this probably won't help much.

The other option is recoding and using lower dimensional arrays and complex indexing, as mentioned. An example of what I mean by this is the year and age specific movement estimation. The estimate T parameters are a matrix, then these are assigned to the appropriate spot in the movement matrix using various indices and counters as below:

G(j,i)=mfexp(ln_T_YR_AGE(j+sum(nregions)*(a-1)+sum(nregions)*(nages-1)*(y-1),i-1));

I think there is a way to do something similar with F when there are differing number of fleets per region, but it is hard for me to envision in a general way without adding extra estimated parameters that are then not actually used (e.g., having 7 parameters in one area and only 4 in another...but then the difference in parameters would still be part of the estimated matrix yet not used for anything).

A quick and dirty approach would be to just add either a fleet specific estimated F vector (with index of region) or a region specific F matrix with index of fleets. I don't imagine this would take much time, but you would just have to make sure you appropriately replace the existing F matrix and index it correctly throughout the code. However, there might be some unforeseen issues like indices for observed and predicted values by fleet, which may prevent this from being a quick solution (i.e., you may have to replace more than just the estimated F vector).

Finally, you could just make a simplifying assumption with the data, either the way you suggest or by condensing down the number of fleets to be the same across regions. There are probably a number of ways to go about that, so I will refrain from providing my opinions. I'll just note that I feel that in a lot of instances it wouldn't necessarily be possible to model the full fleet complexity, so exploring different options to deal with and/or reduce that complexity is probably a worthwhile discussion point for this experiment and your presentations.

**Comment by brianlangseth-NOAA** [comment]
Based on fleet structure in #25 

Fleet 1,2,7 is in areas 1, 2, and 4
Fleet 3 is in areas 1, 2, 3, and 4
Fleet 46 is in areas 1, 2, and 4
Fleet 5 is in area 1

If we simplified we could ignore fleet 5 and area 3, and the remaining three fleets would all be present in areas 1, 2, and 4.

**Comment by brianlangseth-NOAA** [comment]
@AmySchueller-NOAA and @JDeroba 

Im updating the OM .dat file. I have the amount of data correct (the debug code is correct, 1541) but my arrays are wrong sized. Im getting this error 

> debug = 1541
> If debug != 1541 then .dat file not setup correctly
> input read
> parameters set...PARAMETER SECTION FINISHED
> Error: Invalid index 2 used for array range [1, 1] in "dvar_matrix& dvar3_array::operator () (int i)".
> array bound exceeded -- slice index too high

Im going to start with the big arrays first, but for sanitys sake if I have a variable

`#SSB_zero_appor(1,np,1,nreg)`

does it matter if its read in as `0.6 0.6 0.6 0.6` or  
`0.6
0.6
0.6
0.6`

**Comment by JDeroba** [comment]
@brianlangseth-NOAA @AmySchueller-NOAA 
To my knowledge and experience, no, it doesn't matter whether it is read in as four rows or one row. ADMB reads values one at a time, sequentially; either top to bottom or left to right. Although having played with the dataMunge recently I wish we had done it consistently everywhere. Larry Jacobson once told me that he did have troubles in ADMB when values were separated by a 'tab' instead of just a space. He had better performance with just using spaces. I've never been able to reproduce his problems, however, even when I forced tabs all over the place. Note that tabs between values usually happens when you copy and paste input data from excel, which is not what we're doing anywya.

**Comment by brianlangseth-NOAA** [comment]
Reading in data seems pretty robust, and Ive tested row versus columns and it doesn't seem to matter. Im at a loss as to how to diagnose within the .tpl. I have heavily pasted from excel for the 4 area model (arrays across 4 areas, 256 yrs, and 28 ages kind of requires it!) but based on your experience the tab doesn't seem like the issue. 

Ive gone through and cout various subvectors of the arrays and they seem to come out ok. My next solution is to add cout statements within the procedures section to see where the issue is happening. Hopefully I can get something to start ok and can move down to make progress. Any other ideas on how to diagnose where this is happening?

**Comment by brianlangseth-NOAA** [comment]
Well, I found the issue. I had failed to adjust the max_reg value for setting up the random numbers to be greater than the number of fleets. I had it at 1, it should be 4. 

+1 to systematic error checking by hand

**Comment by JDeroba** [comment]
Overall, I'd say that is good news.

**Comment by brianlangseth-NOAA** [comment]
Commit f3be796 adds automatic data loading for a four area model. This version used an updated OM.dat file so many checks from the one area model were unneeded. With that said their remains some hard-coding in that this version is based on a reduced fleet assumption from the get go. For going back to seven fleets, we would need to recode some sections

Remaining tasks:

- [ ] confirm .dat file is read properly by the EM.tpl
- [ ] confirm multidimensional arrays are ordered properly and being read is as intended (e.g. matrix of yrs by areas*fleets, or matrix of yrs*areas x fleets)

**Comment by brianlangseth-NOAA** [comment]
Commit c4e6f1a adds automatic data loading for a four area model (data loading_4areas.R). The version used an updated OM.dat file so many checks from the one area model were unneeded. With that said their remains some hard-coding in that this version is based on a reduced fleet assumption from the get go. For going back to seven fleets, we would need to recode some sections

Remaining tasks:

- [ ] confirm .dat file is read properly by the EM.tpl
- [ ] confirm multidimensional arrays are ordered properly and being read is as intended (e.g. matrix of yrs by areas*fleets, or matrix of yrs*areas x fleets)

**Comment by brianlangseth-NOAA** [comment]
Commit 056c220 added automation for having 7 fleets for the 4 area data_loading script.
