### ISSUE TITLE
parameter bound issue(s)

### ISSUE THREAD

**Issue by JDeroba** [brianlangseth-NOAA/Spatial-Workshop-SPASAM#47]
In the process of trying to get 100 reasonable, single area, fits completed, I discovered that our initial, single dataset fit had several parameters hitting bounds. These were mostly related to sel_beta3 and sel_beta4, but there could be others. Generally, we need to setup a parameter bound check for all parameters. For the simulation exercise, we should be as vigilante as possible, with special attention to selectivity and q parameters. The data_loading scripts can be easily amended to change the bounds.

**Comment by brianlangseth-NOAA** [comment]
Decisions made to improve on the model so as to have more 100 datasets more reasonable include 
-increasing bounds (was this accurate)
-Fix domed selectivity to be logistic (was this only for one fleet? we only had 1 fleet with domed right)
-Increase sample size for fleet 5 to 25 (matches fleet 7)

These improved performance. Previously X of the 100 datasets were hitting bounds or had high gradients, whereas after these chances, X of th 100 datasets were hitting bounds or had high gradients. 

@JDeroba Could you update this comment with accurate information. Hit the three dots in the upper right of the comment and select edit, and then directly edit any corrrections.
