### ISSUE TITLE
cant build ADMB .exe

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [brianlangseth-NOAA/Spatial-Workshop-SPASAM#51]
@JDeroba have you gotten this error? My guess is that there is some issue where IDE isn't reading from where I have ADMB correctly. My proposed solution is to redownload IDE. 

Error: Nothing to build

Builds AD Model Builder executable or library.

Release Version: 12.0
Location: C:\admb\admb120-gcc493-win64\bin\

Usage: admb [-c] [-d] [-g] [-r] [-f] model [src(s)]

Options:
 -c     Build only object file(s) (.obj).
 -d     Build a dynamic library (.dll).
 -g     Build with debug symbols.
 -r     Build Random effects library (ADMB-RE).
 -f     Build with Fast optimized mode library (no error checking).
        By default, admb script will include error checking in the build.
 model  TPL file (ie 'simple.tpl' or the filename 'simple' with no .tpl
        extension)
 src(s) C/C++ Source file(s) containing classes, methods and variables that
        are used in model.

Compilation finished at Thu Dec 22 11:22:49

**Comment by brianlangseth-NOAA** [comment]
@JDeroba Your sage advice came through. The model name I was trying to run was "YFT_2area_4fleets_F0.0001". Removing the "." and reduce the length of the name worked. I tried "YFT" and the exe was built just fine.

**Comment by JDeroba** [comment]
Boom!

Cori was home sick this week Monday-Wednesday. So I have gotten nowhere on
SPASAM work. I have time next week, however. My plan is still to try to
advance your two-area model.

JJD
