### ISSUE TITLE
YFT .dat files not working with current EM .tpl

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [brianlangseth-NOAA/Spatial-Workshop-SPASAM#6]
@JDeroba I ran the TIM_OM_all .dat file, saved the .rep as TIM_EM.dat and then tried to run with the current .tpl for the EM. I could get it to compile but the data output was 0 suggestion something is up. Im assuming you got these .dat files to run just fine. What am I missing?

**Comment by JDeroba** [comment]
@brianlangseth-NOAA I get the same problem. I'm not sure how that slipped through the cracks. I just traced the problem to when I added YFT specific biological data. I must be missing a value somewhere. I'll troubleshoot it now and push new files when I fix the problem.

**Comment by brianlangseth-NOAA** [comment]
@JDeroba Ive spent some time looking into this and the issue is with the "abund_frac_age_region" of the OM report file (there are nan values). If the nan's are set to 1 then the EM runs. Currently Im not sure why the OM would estimate these (likely dividing by a zero in the initialization for the first year)

I know that is contrary to my stated desire of not duplicating but I need to refresh my admb skills, and am posting this in case you haven't had the time to look into the issue yet.

**Comment by JDeroba** [comment]
I was working on it when you sent your last message. Thanks for the clue! I figured it out. The input init_abund vector had zeros for a few of the oldest ages. I put positive values there and everything works. I haven't really dug in to see how well it works, but I get the proper debug number returned. I'll post a new "all.dat" and close this issue.
