### ISSUE TITLE
TO DO: Age length key

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [brianlangseth-NOAA/Spatial-Workshop-SPASAM#8]
@AmySchueller-NOAA and @JDeroba I need help with getting length comps into age comps. This requires an age-length key but without co-collected ages and lengths Im struggling with coming up with a solution on how to do this. I feel like it should be simple. Have either of you done this before?

**Comment by JDeroba** [comment]
There are instructions somewhere for how to do that; i.e., from Caren or someone with YFT OM knowledge. I won't get to it today (12/17), but should have time next week.

**Comment by brianlangseth-NOAA** [comment]
The [questions section](https://github.com/carenbarcelo-NOAA/Spatial-Assessment-Modeling-Workshop/discussions/6) suggests "you can use the growth curve and CV of length at age to convert." The problem is that the details are not coming to me at the moment.

**Comment by JDeroba** [comment]
From an email Goethel sent on August 24, 2021:
"So the consensus seems to be that we aren't providing age comps directly and that you should just develop an age-length key and back calculate age from equation 1 in the OM doc with a CV of 0.1. providing only length comps is meant to match tuna data, soooo.... (not really sure why we didn't just provide both age and length data, but I've lost enough battles in that group to know its not worth pushing things)."

**Comment by brianlangseth-NOAA** [comment]
I still can't figure out even what equation 1 means. It is not well explained. Will leave for Friday's discussion.

**Comment by JDeroba** [comment]
That equation is definitely screwed up and I couldn't get it to work either. But, I think I was able to create an age-length-key based on the mean lengths at age provided in Table A1. See the alk.R script I just uploaded. There is basically no overlap in P(A|L) until you get to the most extreme oldest and largest fish. These things must grow crazy fast, and CV=0.1 limits the amount of overlap too.

**Comment by brianlangseth-NOAA** [comment]
@JDeroba Do age-length keys typically assume normal or lognormal error? In other words is the distribution of lengths around an age normal or lognormal?

I worked up ALK.R with the bin sizes we are using. There is a problem in that the distributions are so tight that there are some length bins that should not have any fish in them (see the attached file). Thus for some length bins (the length comps cover all but the extreme lengths) there are no probabilities for assigning to ages. 

The solution is one of two options dependent on our distribution choice. If we assume a normal distribution, then we need to adjust the sd of pnorm to have a constant CV of 0.1. If we assume a lognormal distribution, we change to plnorm. In both cases the distribution widens much more and all lengths have non-zero probabilities for ages. 

[alk.csv](https://github.com/brianlangseth-NOAA/Spatial-Workshop-SPASAM/files/7916996/alk.csv)

**Comment by brianlangseth-NOAA** [comment]
Thanks Jon. I have lognormal right now for that exact reason. If we need to change its easy to do so.

**Comment by AmySchueller-NOAA** [comment]
I think that lognormal should be good.  I would typically look at the data to determine it when fitting a growth curve, but if data aren't available, then lognormal is generally my default.

Amy
